version: '3.8'

services:
  api:
    build: .
    container_name: mottu-bff
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
